#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  2 06:10:06 2020

@author: nasif
"""

 
def revc(DNA):
     c = {'A':'T', 'T':'A', 'C':'G', 'G':'C'}
 
     REVC = ''
     for bp in DNA:
         REVC = c[bp] + REVC
     return REVC
 
REVC = revc('CAGCATACATAAACGCCCTGACAGATATGCACAATACAAGAAATTCCCCGTGGGATAGTTCCGTCCCTAGTTAATCAAAGCTCTTCGAAACTAAAAAGCGTTGGAGTTCCCTATGTCGTTAAGTTTGGCTCTTTTGTGATCTTTTACACTCGAAAAGCAACGGGACGGATATGAACTAACGTTTTGTTGACGTTCACTGAAACCTCACGTTATATGGCAATTCACAGCAAGCTAGACCTAGCAGCTGGAGCAGGAAGAGATAGTCAGTAGATCCGAACCTATGATGGACCTTACAGCCTAGGTAGGGAAGGGGATGGAAGTGCGAACCCCGCGTCATATATTCCTGTACGTATGCTAGAGGTTGCCCTTCACTGTGCCCGTTCACCTCTTCTCCTCAATCTGAACACCTGTACATCAAGTTGGGCCAACTAGCGTACGCCGATCGCCCGTAGCTAGTTCCGAAGGTTGCCTACCACTTAAAAATAACTTTGCTCCCCTTGGTCAATGCACGATAGACACAATGTAGGTCCCATGTATCCAGCGCAAGGGATGGTGCATCCGCGACGTCATAGGTAAGCGGCTATCGGCACGGCCCAAACACAGGGCCTAAGCTTCTTTTAGTCCTCCATCCCAATGCAGTCCGTATTTCTTTTCACTTCCCCTAGGGCTCGGTAGAAGTGTACAACCTGGTTACAATCGCCTACAAAGAGAGCTTTTTAGGTGCTGATCCCGTCAGTATAGGTCGTCACTCACGCTACTTCACGCACGCCGAGCTGCATGCGAGGTGGCTCCTAACTTGTAAGCTAGGGTATCATAATAACGTCGTTCT')
print(REVC)
 
